name: Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  CPPCheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CPPCheck
      run: sudo apt-get install cppcheck

    - name: Run CPPCheck
      run: |
        make cppcheck

  GoogleTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Checkout
      run: sudo apt-get install docker

    - name: Execute GoogleTest
      run: |
        chmod 777 ./linux-presubmit.sh
        ./linux-presubmit.sh

  Build:
    runs-on: ubuntu-latest
    needs:
      - CPPCheck
      - GoogleTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        Echo build

  #CreatePR:
  #  runs-on: ubuntu-latest
  #  needs: Build

  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3

  #  - name: Create PR
  #    uses: peter-evans/create-pull-request@v3
  #    with:
  #      token: ${{ secrets.GITHUB_TOKEN }}
  #      commit-message: 'Auto-generated PR'
  #      title: 'Auto-generated PR'
  #      body: 'This PR was automatically generated.'
  #      branch: develop
