name: Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  CPPCheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CPPCheck
      run: sudo apt-get install cppcheck

    - name: Run CPPCheck
      run: |
        make cppcheck
        echo ${GITHUB_EVENT_NAME}

  GoogleTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Checkout
      run: sudo apt-get install docker

    - name: Execute GoogleTest
      run: |
        chmod 777 ./scripts/GoogleTest.sh
        ./scripts/GoogleTest.sh

  Build:
    runs-on: ubuntu-latest
    needs:
      - CPPCheck
      - GoogleTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        make

  CreatePRToMaster:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref_name == 'develop' && '${GITHUB_EVENT_NAME}' == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_no_diff: true

  CreatePRToDevelop:
    runs-on: ubuntu-latest
    needs: Build
    if: (github.ref_name != 'develop' && github.ref_name != 'master') && '${GITHUB_EVENT_NAME}' == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_no_diff: true
          target_branch: develop

  SendTo42:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref_name == 'master' && '${GITHUB_EVENT_NAME}' == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
            host: vogsphere-v2.42sp.org.br
            private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Envia para a 42
        run: |
          git clone ${{ secrets.REPO_TARGET }} repo_target
          cd repo_target
          cp -rf ../Makefile Makefile
          cp -rf ../includes includes
          cp -rf ../scripts scripts
          cp -rf ../src src
          cp -rf ../.vscode .vscode
          cp -rf ../.editorconfig .editorconfig
          cp -rf ../.gitignore .gitignore
          git status
          #git add *
          #git commit -m "Push automatizado"
          #git push

