name: Clonar Repositório SSH

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan github.com > ~/.ssh/known_hosts

    - name: Clonar Repositório
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add ~/.ssh/id_rsa
        git clone "${{ secrets.REPO_TARGET }}" teste
