name: Clonar Repositório SSH

on:
  push:
    branches:
      - develop # Você pode ajustar para a branch que deseja
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts

    - name: Clonar Repositório
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add ~/.ssh/id_rsa
        git clone git@vogsphere-v2.42sp.org.br:vogsphere/intra-uuid-29d4d6d4-e1fa-4697-b333-96efaa638cd8-3582182 teste
        ls
        cd teste
        ls
