name: Deploy

on:
  push:
    branches:
      - all
  pull_request:
    branches:
      - develop
      - master

jobs:
  CPPCheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CPPCheck
      run: sudo apt-get install cppcheck

    - name: Run CPPCheck
      run: |
        make cppcheck

  GoogleTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Checkout
      run: sudo apt-get install docker

    - name: Execute GoogleTest
      run: |
        echo ${{ github.ref }}
        echo ${{ github.base_ref }}
        echo ${{ github.head_ref }}
        echo ${{ github.ref_name }}
        echo github.ref

  Build:
    runs-on: ubuntu-latest
    needs:
      - CPPCheck
      - GoogleTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        make

  CreatePR:
    runs-on: ubuntu-latest
    needs: Build
    if: github.head_ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Full deploy action
          allow_no_diff: true

  SendTo42:
    runs-on: ubuntu-latest
    needs: Build
    if: github.head_ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000

      - name: Envia para a 42
        run: |
          echo Enviou
