name: Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  #CPPCheck:
  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3

  #  - name: Install CPPCheck
  #    run: sudo apt-get install cppcheck

  #  - name: Run CPPCheck
  #    run: |
  #      make cppcheck

  #GoogleTest:
  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3

  #  - name: Install Checkout
  #    run: sudo apt-get install docker

  #  - name: Execute GoogleTest
  #    run: |
  #      chmod 777 ./scripts/GoogleTest.sh
  #      ./scripts/GoogleTest.sh

  #Build:
  #  runs-on: ubuntu-latest
  #  needs:
  #    - CPPCheck
  #    - GoogleTest

  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v3

  #  - name: Build
  #    run: |
  #      make

  #CreatePR:
  #  runs-on: ubuntu-latest
  #  needs: Build
  #  if: github.ref_name == 'develop'

  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 1000

  #    - name: Create pull request
  #      uses: devops-infra/action-pull-request@v0.5.5
  #      with:
  #        github_token: ${{ secrets.GITHUB_TOKEN }}
  #        title: Full deploy action
  #        allow_no_diff: true

  SendTo42:
    runs-on: ubuntu-latest
    #needs: Build
    #if: github.ref_name == 'master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
            host: vogsphere-v2.42sp.org.br
            private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Envia para a 42
        run: |
          git clone git@vogsphere-v2.42sp.org.br:vogsphere/intra-uuid-29d4d6d4-e1fa-4697-b333-96efaa638cd8-3582182 a
