name: Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  CPPCheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CPPCheck
      run: sudo apt-get install cppcheck

    - name: Run CPPCheck
      run: |
        make cppcheck

  GoogleTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Checkout
      run: sudo apt-get install docker

    - name: Execute GoogleTest
      run: |
        chmod 777 ./linux-presubmit.sh
        ./linux-presubmit.sh

  Build:
    runs-on: ubuntu-latest
    needs:
      - CPPCheck
      - GoogleTest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        make

  CreatePR:
    runs-on: ubuntu-latest
    needs: Build

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Criar Pull Request
      run: |
        git config user.name "PedroYRSousa"
        git config user.email "yagosousa2512@gmail.com"
        hub pull-request -m "Merge da branch develop para master" -b master -h develop
